name: Auto-format on main

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  format:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Format and tidy
        run: |
          gofmt -s -w .
          go mod tidy

      - name: Commit changes if any
        run: |
          if ! git diff --quiet; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "chore(format): auto-format code [skip ci]"
            git push
          else
            echo "No formatting changes."
          fi

